### ISSUE TITLE
why propagate back to target box (bottom[1]) in Smooth_L1_Loss?

### ISSUE THREAD

**Issue by apoliver** [rbgirshick/caffe-fast-rcnn#1]
Hi,

I am wondering why need propagate back to bottom[1] in Smooth_L1_Loss? Is it strange to propagate to target box which actually is label for bbox regression?

Thanks much!

This is in the following code:
for (int i = 0; i < 2; ++i) {
    if (propagate_down[i]) {
      const Dtype sign = (i == 0) ? 1 : -1;
      const Dtype alpha = sign \* top[0]->cpu_diff()[0] / bottom[i]->num();
      caffe_gpu_axpby(
          bottom[i]->count(),              // count
          alpha,                           // alpha
          diff_.gpu_data(),                // x
          Dtype(0),                        // beta
          bottom[i]->mutable_gpu_diff());  // y
    }
  }
}

**Comment by rbgirshick** [comment]
Smooth L1 loss can be used in cases where you do want to bprop to both inputs (e.g., in a "siamese" network). In the case of Fast R-CNN, we don't need derivatives for the bbox regression labels, but the layer is more general than its use in Fast R-CNN.

**Comment by apoliver** [comment]
I see. Thanks, Ross.
