### ISSUE TITLE
Merge the fast-rcnn-cleanup branch into the official Caffe to avoid straying from the Caffe master branch and increasing the maintenance cost to keep updated

### ISSUE THREAD

**Issue by futurely** [rbgirshick/caffe-fast-rcnn#2]

**Comment by y22ma** [comment]
+1

**Comment by hazirbas** [comment]
Hi,

Did anyone manage to merge fast-rcnn into caffe master branch?

Thanks.

**Comment by Austriker** [comment]
@futurely @y22ma @canerhazirbas @rbgirshick 
I have created a [PR 4163](https://github.com/BVLC/caffe/pull/4163) based on the [commit](https://github.com/rbgirshick/caffe-fast-rcnn/commit/0dcd397b29507b8314e252e850518c5695efbb83) used in [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn).

It's almost ready to merge but I have two issues with the test that I haven't solved yet !
If you have any ideas !

**Comment by zimenglan-sysu-512** [comment]
@Austriker i merge the caffe-fast-rcnn with the [newest caffe master branch] from (https://github.com/BVLC/caffe),  it seems to merge successfully without any conflicts. and then i `make -j8 && make pycaffe -j8`, it still looks good. But, when i run the demo in `tools/demo.py` of `faster-rcnn`, it got some problem like this:

I0701 16:42:13.574218  2278 net.cpp:156] Memory required for data: 117496524
I0701 16:42:13.574223  2278 layer_factory.hpp:77] Creating layer proposal
I0701 16:42:13.583842  2278 net.cpp:91] Creating Layer proposal
I0701 16:42:13.583858  2278 net.cpp:425] proposal <- rpn_cls_prob_reshape
I0701 16:42:13.583864  2278 net.cpp:425] proposal <- rpn_bbox_pred
I0701 16:42:13.583869  2278 net.cpp:425] proposal <- im_info
I0701 16:42:13.583875  2278 net.cpp:399] proposal -> rois
Traceback (most recent call last):
  File "demo.py", line 135, in <module>
    net = caffe.Net(prototxt, caffemodel, caffe.TEST)
AttributeError: can't set attribute

did you ever seen this before?
i don't find out what the problem it is!

@rbgirshick can you do me a favor?
thanks!

**Comment by Austriker** [comment]
@zimenglan-sysu-512 I have a working py-faster-rcnn with an up-to-date caffe :
[Austriker/py-faster-rcnn](https://github.com/Austriker/py-faster-rcnn)

**Comment by stonycat** [comment]
@zimenglan-sysu-512 I meet the same problem, have you solved it ?

**Comment by zimenglan-sysu-512** [comment]
@stonycat hi,  after merge, i just Remove `"self_.attr("phase") = static_cast<int>(this->phase_);"` from `include/caffe/layers/python_layer.hpp` after merging.

**Comment by stonycat** [comment]
@zimenglan-sysu-512 thank you for your reply.Have you met conflicts when you merge caffe master branch into caffe-fast-rcnn?

**Comment by zimenglan-sysu-512** [comment]
hi @stonycat i don't have any conflicts.

**Comment by mdadhich** [comment]
@Austriker if I just clone faster_rcnn from your git, do I have to build everything I have done from Ross's. and will it work if I build it using cmake and not make as I am using Red-Hat. Thanks 
Please have a look, my problem is described here -  https://github.com/rbgirshick/py-faster-rcnn/issues/494

**Comment by soulslicer** [comment]
Made it work with pascal:

https://github.com/soulslicer/caffe-fast-rcnn

Just change proposal_layer.py

```
     def setup(self, bottom, top):
         # parse the layer parameter string, which must be valid YAML
-        layer_params = yaml.load(self.param_str_)
+        layer_params = yaml.load(self.param_str)
 
         self._feat_stride = layer_params['feat_stride']
         anchor_scales = layer_params.get('scales', (8, 16, 32))
@@ -61,7 +61,7 @@ class ProposalLayer(caffe.Layer):
         assert bottom[0].data.shape[0] == 1, \
             'Only single item batches are supported'
 
-        cfg_key = str(self.phase) # either 'TRAIN' or 'TEST'
+        cfg_key = 'TEST' if self.phase == 1 else 'TRAIN'

```
